const categories = {
  style: ["quick sketch", "cartoon", "detailed", "realistic", "simplified"],
  theme: {
    stillLife: [
      "food",
      "vehicles",
      "furniture",
      "flowers&plants",
      "sculptures",
      "decoration",
      "kid's toys",
    ],
    animal: [
      "dog",
      "cat",
      "rabbit",
      "bird",
      "horse",
      "snake",
      "fish",
      "imaginary",
      "mouse",
      "marine",
      "mythical",
      "spider",
      "bug",
      "farm animal",
      "frog",
      "crocodile",
      "deer/stag",
      "wolf",
      "hedgehog",
    ],
    architecture: [
      "modern",
      "victorian",
      "middle ages",
      "chinese",
      "japanese",
      "western",
      "futuristic",
    ],
    landscape: [
      "sandy beach",
      "rocky beach",
      "farmlands",
      "village",
      "small city",
      "big city",
      "lake",
      "forest",
      "island",
    ],
    people: ["child", "teen", "yound adult", "woman", "man", "LGBQT+", "elder"],
  },
  genre: [
    "fantasy",
    "horror",
    "children's book",
    "anime",
    "romantic",
    "gloomy",
    "sci-fi",
  ],
  technique: {
    digital: [
      "one-line",
      "specific brush",
      "use pen",
      "use fingers",
      "no eraser",
      "calligraphy",
    ],
    oil: [],
    acryl: [
      "watery",
      "no added water",
      "thick and thin brush",
      "sponge",
      "spatula",
    ],
    penAndPaper: [
      "pencils",
      "coal pencil",
      "pastels",
      "hard pencils",
      "soft pencils",
      "one-line",
      "calligraphy",
    ],
    waterColors: [
      "gradient",
      "very watery",
      "wet paper",
      "dry paper",
      "drops",
      "calligraphy",
    ],
  },
  coloration: [
    "mono-colored",
    "two-colored",
    "three-colored",
    "black/white",
    "saturated",
    "pale",
    "dark",
    "complementary colors",
    "sepia",
    "dark with lighting effects",
  ],
  characterDesign: {
    species: ["human", "non-human", "fantasy being", "animal", "alien"],
    age: ["very young", "young", "adolescent", "adult", "old", "very old"],
    gender: ["male", "female", "non-binary", "other"],
    environment: [
      "ocean",
      "forest",
      "meadow",
      "rural village",
      "urban city",
      "space",
    ],
    epoch: [
      "stone age",
      "bronze age",
      "middle ages",
      "18th century",
      "20th century",
      "present",
      "near future",
      "far future",
    ],
  },
};
