export const items = {
  style: [
    "Quick Sketch",
    "Cartoon",
    "Detailliert",
    "Realistisch",
    "Simpel",
    "Abstrakt",
  ],
  theme: {
    stillLife: [
      "Essen",
      "Fahrzeug",
      "Möbelstück",
      "Blumen & Pflanzen",
      "Skulptur",
      "Deko",
      "Spielzeug",
    ],
    animal: [
      "Hund",
      "Katze",
      "Hase",
      "Vogel",
      "Pferd",
      "Schlange",
      "Fisch",
      "Imaginär",
      "Maus",
      "Nagetier",
      "Haustier",
      "Meereslebewesen",
      "Spinne",
      "Insekt",
      "Bauernhof Tier",
      "Frosch",
      "Krokodil",
      "Reh/Hirsch",
      "Wolf",
      "Igel",
      "Wildtier",
      "Löwe",
      "Elefant",
      "Giraffe",
    ],
    architecture: [
      "Modern",
      "Viktorianisch",
      "Mittelalter",
      "Asiatisch",
      "Westlich",
      "Futuristisch",
    ],
    landscape: [
      "Sandstrand",
      "Küste",
      "Farm/Felder",
      "Dorf",
      "Kleinstadt",
      "Großstadt",
      "Fluss",
      "Wald",
      "Insel",
      "See",
      "Garten",
    ],
    people: [
      "Kind",
      "Jugendliche(r)",
      "Junge(r) Erwachsene(r)",
      "Frau",
      "Mann",
      "Trans-Mann/-Frau",
      "Senior(in)",
    ],
  },
  genre: [
    "Fantasy",
    "Horror",
    "Kinderbuch",
    "Anime",
    "Romantisch",
    "Düster",
    "Sci-Fi",
  ],
  technique: {
    Digital: [
      "Eine Linie",
      "Nur ein Pinsel",
      "Nicht radieren",
      "Kalligraphie",
      "Beliebige Technik",
    ],
    Ölfarben: ["Beliebige Technik"],
    Acrylfarben: [
      "Wässrig",
      "Ohne Wasser",
      "Schnelle Bewegungen",
      "Schwamm",
      "Spachtel",
      "Beliebige Technik",
    ],
    "Pen&Paper": [
      "Bleistift",
      "Buntstift",
      "Kohlestift",
      "Pastellkreide",
      "Harte Stife",
      "Weiche Stifte",
      "Ein Linie",
      "Kalligraphie",
      "Beliebige Technik",
    ],
    Aquarellfarben: [
      "Farbverlauf",
      "Sehr wässrig",
      "Feuchtes Papier",
      "Trockenes Papier",
      "Tropfen",
      "Kalligraphie",
      "Beliebige Technik",
    ],
  },
  coloration: [
    "Einfarbig",
    "Zweifarbig",
    "Dreifarbig",
    "Mehrfarbig",
    "Schwarz-Weiß",
    "Satte Farben",
    "Blasse Farben",
    "Dunkel",
    "Komplementärfarben",
    "Sepia",
    "Licht-Effekte",
  ],
  characterDesign: {
    Spezies: ["Mensch", "Nicht menschlich", "Fantasiewesen", "Tier", "Alien"],
    Alter: ["Sehr jung", "Jung", "Jugendlich", "Erwachsen", "Alt", "Sehr alt"],
    Geschlecht: ["Männlich", "Weiblich", "Non-Binary", "Unbestimmt"],
    Umgebung: [
      "Meer",
      "Wald",
      "Wiese",
      "Ländliches Dorf",
      "Belebte Stadt",
      "Weltraum",
    ],
    Epoche: [
      "Steinzeit",
      "Bronzealter",
      "Mittelalter",
      "18. Jahrhundert",
      "20. Jahrhundert",
      "Gegenwart",
      "Nahe Zukunft",
      "Ferne Zukunft",
    ],
  },
};
