export const items = {
  style: [
    "Quick Sketch",
    "Cartoon",
    "Detailliert",
    "Realistisch",
    "Simpel",
    "Abstrakt",
    "Pixel Art",
  ],
  theme: {
    stillLife: [
      "Essen",
      "Fahrzeug",
      "Möbelstück",
      "Blumen & Pflanzen",
      "Skulptur",
      "Deko",
      "Spielzeug",
    ],
    animal: [
      "Hund",
      "Katze",
      "Hase",
      "Vogel",
      "Pferd",
      "Schlange",
      "Fisch",
      "Imaginär",
      "Maus",
      "Nagetier",
      "Haustier",
      "Meereslebewesen",
      "Spinne",
      "Insekt",
      "Bauernhof Tier",
      "Frosch",
      "Krokodil",
      "Reh/Hirsch",
      "Wolf",
      "Igel",
      "Wildtier",
      "Löwe",
      "Elefant",
      "Giraffe",
    ],
    architecture: [
      "Modernes Gebäude",
      "Viktorianisches Gebäude",
      "Mittelalterliches Gebäude",
      "Asiatisches Gebäude",
      "Westliches Gebäude",
      "Futuristisches Gebäude",
    ],
    people: [
      "Kind",
      "Jugendliche(r)",
      "Junge(r) Erwachsene(r)",
      "Frau",
      "Mann",
      "Trans-Mann/-Frau",
      "Senior(in)",
      "Nico",
    ],
  },
  genre: [
    "Fantasy",
    "Horror",
    "Kinderbuch",
    "Anime",
    "Romantisch",
    "Düster",
    "Sci-Fi",
  ],
  technique: {
    "Digitales Medium": [
      "Eine Linie",
      "Nur ein Pinsel",
      "Nicht radieren",
      "Kalligraphie",
      "Beliebige Technik",
    ],
    Ölfarben: ["Beliebige Technik"],
    Acrylfarben: [
      "Wässrig",
      "Kein Wasser",
      "Schnelle Bewegungen",
      "Schwamm",
      "Spachtel",
      "Beliebige Technik",
    ],
    "Pen&Paper": [
      "Bleistifte",
      "Buntstifte",
      "Kohlestifte",
      "Marker",
      "Pastellkreide",
      "Wachsmalstifte",
      "Ein Linie",
      "Kalligraphie",
      "Beliebige Technik",
    ],
    Aquarelle: [
      "Farbverlauf",
      "Sehr wässrig",
      "Feuchtes Papier",
      "Trockenes Papier",
      "Tropfen",
      "Kalligraphie",
      "Beliebige Technik",
    ],
  },
  coloration: [
    "Einfarbig",
    "Zweifarbig",
    "Dreifarbig",
    "Mehrfarbig",
    "Schwarz-Weiß",
    "Satte Farben",
    "Blasse Farben",
    "Dunkel",
    "Komplementärfarben",
    "Sepia",
    "Licht-Effekte",
  ],
  background: [
    "Sandstrand",
    "Küste",
    "Farm/Felder",
    "Dorf",
    "Kleinstadt",
    "Großstadt",
    "Fluss",
    "Wald",
    "Insel",
    "See",
    "Garten",
  ],
};
